openapi: 3.0.1
info:
  title: Czech Open Banking Standard
  version: 8.0.0
  description: ''
  contact:
    name: Petr Michalik
    email: pmichalik@csas.cz
servers:
  - url: 'https://api.bank.cz'
    description: An openbanking test server
components:
  securitySchemes:
    OAuth2:
      description: |
        This API uses OAuth 2 with the implicit grant flow.
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          scopes:
            AISP: Access to all services within AISP
            aisp.accounts: Access to an overview of accounts
            aisp.balances: Access to information about balances
            aisp.transactions: Access to the overview of transactions
            aisp.directdebits: Access to the direct debits
            aisp.standingorders: Access to the standing orders
            PISP: Access to all services within PIS
            pisp.payments: Option to initiate payment
            pisp.directdebits: Ability to initiate a direct debits
            pisp.standingorders: Ability to initiate a standing order
            pisp.accounts: >-
              Ability to obtain a list of accounts from those ASPS that offer a
              list of accounts together with PIS servicesA
    ClientCert:
      description: |
        Use of an x509 client certificate within mutual TLS
      type: http
      scheme: mutualTLS
    ApiKey:
      description: >
        An optional string issued to a communicating third party as the call
        identifier of that party primarily serving as a communication
        configuration element.
      type: apiKey
      in: header
      name: API-key
paths:
  /my/accounts:
    get:
      summary: List of client payment accounts
      description: >
        Paged list of client accounts. Each account contains a unique id usable
        for URI referencing, e.g. for the account detail.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** yes
          * **Sorting:**  yes
          * **Filtering:**  no
      operationId: '-getAllAccounts'
      tags:
        - Account information
      security:
        - OAuth2:
            - AISP
            - aisp.accounts
          ClientCert: []
          ApiKey: []
  '/my/accounts/{id}/balance':
    get:
      summary: Account balance
      description: >
        The balance of the specific client account according to the reference id
        account.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getAccountsBalances'
      tags:
        - Account information
      security:
        - OAuth2:
            - AISP
            - aisp.balances
          ClientCert: []
          ApiKey: []
  '/my/accounts/{id}/transactions':
    get:
      summary: Overview of transactions
      description: |
        Paged list of transactions of a selected client account.

        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** yes
          * **Sorting:**  yes
          * **Filtering:**  no
      operationId: '-getAccountsTransactions'
      tags:
        - Account information
      security:
        - OAuth2:
            - AISP
            - aisp.transactions
          ClientCert: []
          ApiKey: []
  /my/payments/awaiting:
    get:
      summary: Overview of awaiting transactions
      description: >
        Paged list of client’s awaiting payments on all accounts. Each payment
        contains a unique id usable for URI referencing, e.g. for the payment
        detail.

        Additionally, the debtorAccount contains an API account id to call the
        account details resource to which the payment order is issued.
      operationId: '-getAwaitingTransactions'
      tags:
        - Account information
      security:
        - OAuth2:
            - AISP
          ClientCert: []
          ApiKey: []
  '/my/accounts/{id}/payments/awaiting':
    get:
      summary: Overview of awaiting transactions on specific user account
      description: >
        Paged list of client’s awaiting payments on specific accounts. Each
        payment contains a unique id usable for URI referencing, e.g. for the
        payment detail.

        Additionally, the debtorAccount contains an API account id to call the
        account details resource to which the payment order is issued.
      operationId: '-getAccountAwaitingTransactions'
      tags:
        - Account information
      security:
        - OAuth2:
            - AISP
          ClientCert: []
          ApiKey: []
  /my/standingorders:
    get:
      summary: List of client’s standing orders
      description: >
        Paged list of client’s standing orders. Each standing order contains a
        unique id usable for URI referencing, e.g. for the standing order
        detail.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** yes
          * **Sorting:**  yes
          * **Filtering:**  no
      operationId: '-getStandingorders'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - AISP
            - aisp.standingorders
          ClientCert: []
          ApiKey: []
    post:
      summary: New standing order - instruction initiation
      description: |
        Resource for entering a new standingorder.
      operationId: '-postNewStandingOrder'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PISP
            - pisp.standingorders
          ClientCert: []
          ApiKey: []
  '/my/standingorders/{transactionIdentification}':
    get:
      summary: Detail about the standing order
      description: >
        Resource for get detail about the standing order. 

        It is at the choice of each bank whether to return details of any
        client’s standing order or just those that the client has established
        through a particular TPP.


          **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getStandingorder'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PISP
            - AISP
            - pisp.standingorders
            - aisp.standingorders
          ClientCert: []
          ApiKey: []
    delete:
      summary: Resource to delete standing order.
      description: >
        Resource to delete unauthorised and authorised standing orders. 


        Deleting of an authorised standing order must be followed by the
        authorisation process which is identical with the new standing order
        authorisation process.


          **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-deleteStandingorder'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PIS
            - pisp.standingorders
          ClientCert: []
          ApiKey: []
    put:
      summary: Update standing order - instruction initiation
      description: |
        Resource for change of standing order specification.
      operationId: '-updateStandingOrder'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PISP
            - pisp.standingorders
          ClientCert: []
          ApiKey: []
  '/my/standingorders/{transactionIdentification}/status':
    get:
      summary: Resource for getting status of the standing order
      description: |
        Resource for getting status of the standing order.

          **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getStandingorderStatus'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PISP
            - pisp.standingorders
          ClientCert: []
          ApiKey: []
  '/my/standingorders/{transactionIdentification}/sign/{signId}':
    get:
      summary: Step I. Standing Order authorization detail
      description: >
        - To identify the status and scenarios of Standing Order authorization.

        - Part of the response is also the set of scenarios that may contain one
        or more authorisation scenarios. If more scenarios are returned, it is
        up to the client to select what scenario to choose. The power of
        verifying each scenario should correspond to the power of other
        scenarios, or the scenarios are mutually replaceable.

        - Each scenario is defined as the sequence of codes of particular
        authorization methods.

        - Each bank may define and describe in its documentation its own
        authorization scenarios.

        - CODE of authorization methods of these scenarios is used in the
        response of this resource.



        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getStandingOrderAuthorizationDetail'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PISP
            - pisp.standingorders
          ClientCert: []
          ApiKey: []
    post:
      summary: >-
        Step II. Standing Order authorization initiation - specific for each
        bank
      description: >
        - This resource is designed to **start a specific authorization method**
        from the selected scenario.

        - The input is the JSON object containing the required type of
        authorization method - **CODE** and all elements specific for that step.

        - The output of this resource is an overview of values required for
        completing the authorization.

        - **E.g., for CODE corresponding to the federated authorization, the
        response will be URL and parameters for redirecting to the federated
        authorization page.**

        - And, for instance, for CODE corresponding to authorization through the
        OTP code sent by SMS, the response will only be the confirmation of
        sending the code. The sending as such is initiated by the bank.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-postStandingOrderAuthorizationInitiation'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PISP
            - pisp.standingorders
          ClientCert: []
          ApiKey: []
    put:
      summary: >-
        Step III. Standing Order authorization initiation – specific for each
        bank
      description: >
        - An optional resource designed for the finalization of the
        authorization process. 

        - The resource may be purely indicative or returns information on
        whether the authorization process was completed and with what result. 

        - E.g., in the case of federated authorization.

        - Or what input, e.g. for entering the received OTP for the SMS method.

        - Then the output is information on the authorization and also OTP
        verification.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-putStandingOrderAuthorizationInitiation'
      tags:
        - Standing Orders
      security:
        - OAuth2:
            - PISP
            - pisp.standingorders
          ClientCert: []
          ApiKey: []
  '/my/accounts/{id}/directdebits':
    get:
      summary: List of client’s domestic direct debits Consents
      description: >
        Paged list of client’s domestic direct debits Consents. Each domestic
        direct debit Consent (Mandate) contains a unique id usable for URI
        referencing, e.g., for the domestic direct debit detail.


        Additionally, the debtorAccount contains an API account id to call the
        account details resource to which the payment order is issued.
      operationId: '-getDirectDebits'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - AISP
            - aisp.directdebits
          ClientCert: []
          ApiKey: []
    post:
      summary: Domestic direct debit consent - instruction initiation
      description: |
        Resource for entering a new domestic direct debit consent.
      operationId: '-postDirectDebit'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ClientCert: []
          ApiKey: []
  '/my/accounts/{id}/directdebits/{mandateIdentification}':
    get:
      summary: Domestic direct debit Consent detail
      description: >
        Resource for get detail about the domestic direct debit Consent.


        It is at the choice of each bank whether to return details of any
        client’s direct debit Consent or just those that the client has
        established through a particular TPP.
      operationId: '-getDirectDebit'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - AISP
            - aisp.directdebits
          ClientCert: []
          ApiKey: []
    put:
      summary: Domestic direct debit consent change
      description: |
        Resource for change of domestic direct debit Consent specification.
      operationId: '-putDirectDebit'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ClientCert: []
          ApiKey: []
    delete:
      summary: Domestic direct debit Consent delete
      description: >
        Resource for delete of domestic direct debit Consent specification.



        Deleting of an authorised domestic direct debit Consent must be followed
        by the authorization process which is identical with the new domestic
        direct debit Consent authorisation process.
      operationId: '-deleteDirectDebit'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ClientCert: []
          ApiKey: []
  '/my/accounts/{id}/directdebits/{mandateIdentification}/sign/{signId}':
    get:
      summary: Domestic direct debit authorization Step I
      description: |
        First step of direct debit authorization.
      operationId: '-getSignDirectDebit'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ClientCert: []
          ApiKey: []
    post:
      summary: Domestic direct debit authorization Step II
      description: |
        Second step of direct debit authorization.
      operationId: '-postSignDirectDebit'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ClientCert: []
          ApiKey: []
    put:
      summary: Domestic direct debit authorization Step III
      description: >
        - An optional resource designed for the finalization of the
        authorization process. 

        - The resource may be purely indicative or returns information on
        whether the authorization process was completed and with what result. 

        - E.g., in the case of federated authorization.

        - Or what input, e.g. for entering the received OTP for the SMS method.

        - Then the output is information on the authorization and also OTP
        verification.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-putSignDirectDebit'
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ClientCert: []
          ApiKey: []
  /my/payments/directdebit:
    post:
      summary: New direct debit - payment initiation
      description: |
        Resource for entering a new direct debit.
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ApiKey: []
        - ClientCert: []
          ApiKey: []
  '/my/payments/directdebit/{transactionIdentification}':
    get:
      summary: Detail about the direct debit order
      description: |
        Resource for getting the detail about the direct debit order.
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ApiKey: []
        - ClientCert: []
          ApiKey: []
    delete:
      summary: Resource to delete the direct debit order
      description: |
        Resource to delete direct debit order.
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ApiKey: []
        - ClientCert: []
          ApiKey: []
  '/my/payments/directdebit/{transactionIdentification}/status':
    get:
      summary: Resource for getting the status of the direct debit order
      description: |
        Resource for getting the status of the direct debit order.
      tags:
        - Direct Debits
      security:
        - OAuth2:
            - PISP
            - pisp.directdebits
          ApiKey: []
        - ClientCert: []
          ApiKey: []
  /my/payments/balanceCheck:
    post:
      summary: Query for Balance Check
      description: >
        This is the resource for sending a request for balance check in a
        particular payer's payment account. This resource is authorized. Access
        to information must be granted by the client outside the interaction of
        this API before the resource is used.
      operationId: '-postBalanceCheck'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.accounts
          ApiKey: []
        - ClientCert: []
          ApiKey: []
  /my/payments:
    post:
      summary: New payment - payment initiation
      description: |
        Resource for entering a new payment.
      operationId: '-postNewPayment'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  '/my/payments/{paymentId}/status':
    get:
      summary: Payment status.
      description: >
        A resource to display the payment status. It is an entered payment which
        has not been authorised by the client yet or has already been
        authorised, and PISP requires its status


        **Resource characteristics:**
          * **Authorization:**  request does not require the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getPaymentStatus'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  '/my/payments/{paymentId}':
    get:
      summary: Payment info.
      description: >
        A resource to display the information on the entered payment. It is
        payment which is received for authorisation, but has not been authorised
        by the client yet. The resource only works with transactions entered
        through a specific provider. The resource to find out the transaction
        detail. Information on the provider is taken from the certificate or
        information on licence.


        **Resource characteristics:**
          * **Authorization:**  request does not require the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getPaymentInfo'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
    delete:
      summary: Deleting the entered unathorised payment
      description: >
        A resource for deleting the unauthorised payment. Deleting is not
        conditioned by the transaction authorisation as it is not a payment
        received by the bank.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-deleteUnauthorisedPayment'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  '/my/payments/{paymentId}/sign':
    post:
      summary: Generating Authorization ID.
      description: >
        - Generating the authorization ID for payment before the initiation of
        the authorization process. The resource is implemented by banks that do
        not want to generate authorization ID for payment in the response when
        entering a new (unauthorized) payment through the resource POST
        /my/payments.

        - Each bank may define and describe in its documentation its own
        authorization scenarios. The CODE of authorization methods for these
        scenarios is used in the response of this resource.

        - Part of the response is also the set of scenarios that may contain one
        or more authorisation scenarios. If more scenarios are returned, it is
        up to the client to select what scenario to choose. The power of
        verifying each scenario should correspond to the power of other
        scenarios, or the scenarios are mutually replaceable.

        - Each scenario is defined as the sequence of codes of particular
        authorization methods. The code of authorization method is defined by
        the bank and should be described in its own API documentation outside
        the ČOBS standard.



        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-postGeneratingAuthorizationId'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  '/my/payments/{paymentId}/sign/{signId}':
    get:
      summary: Step I. Payment authorization detail
      description: >
        - To identify the status and scenarios of payment authorization.

        - Part of the response is also the set of scenarios that may contain one
        or more authorisation scenarios. If more scenarios are returned, it is
        up to the client to select what scenario to choose. The power of
        verifying each scenario should correspond to the power of other
        scenarios, or the scenarios are mutually replaceable.

        - Each scenario is defined as the sequence of codes of particular
        authorization methods.

        - Each bank may define and describe in its documentation its own
        authorization scenarios.

        - CODE of authorization methods of these scenarios is used in the
        response of this resource.



        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getPaymentAuthorizationDetail'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
    post:
      summary: Step II. Payment authorization initiation - specific for each bank
      description: >
        - This resource is designed to **start a specific authorization method**
        from the selected scenario.

        - The input is the JSON object containing the required type of
        authorization method - **CODE** and all elements specific for that step.

        - The output of this resource is an overview of values required for
        completing the authorization.

        - **E.g., for CODE corresponding to the federated authorization, the
        response will be URL and parameters for redirecting to the federated
        authorization page.**

        - And, for instance, for CODE corresponding to authorization through the
        OTP code sent by SMS, the response will only be the confirmation of
        sending the code. The sending as such is initiated by the bank.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-postPaymentAuthorizationInitiation'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
    put:
      summary: Step III. Payment authorization initiation – specific for each bank
      description: >
        - An optional resource designed for the finalization of the
        authorization process. 

        - The resource may be purely indicative or returns information on
        whether the authorization process was completed and with what result. 

        - E.g., in the case of federated authorization.

        - Or what input, e.g. for entering the received OTP for the SMS method.

        - Then the output is information on the authorization and also OTP
        verification.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-putPaymentAuthorizationInitiation'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  /my/authorizations:
    get:
      summary: Get list of authorizations
      description: >
        Resource to obtain a list of authorization requests for authenticated
        user and TPP.
      operationId: '-getListOfAuthorizations'
      tags:
        - Payment Initiation
      security:
        - OAuth2:
            - PISP
          ClientCert: []
          ApiKey: []
  /accounts/balanceCheck:
    post:
      summary: Query for Balance Check
      description: >
        This is a resource for sending a query for Balance Check in a specific
        payment account of the account payer. The resource is not authorized
        directly by the account holder, through the authorization resource.
        Access to information must be granted by the client outside the
        interaction of this API before the resource is used.
      operationId: '-postAccountsBalanceCheck'
      tags:
        - Balance check
      security:
        - ClientCert: []
          ApiKey: []
  /my/batchpayments:
    post:
      summary: New batch payment - instruction initiation
      description: |
        Resource for entering a new batch payment.
      operationId: '-postNewBatchPayment'
      tags:
        - Batch Payments
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  '/my/batchpayments/{transactionIdentification}':
    delete:
      summary: Delete batch payment
      description: >
        A resource for deleting the unauthorised batch payment. Deleting is not
        conditioned by the transaction authorisation as it is not a payment
        received by the bank.
      operationId: '-deleteBatchPayment'
      tags:
        - Batch Payments
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  '/my/batchpayments/{transactionIdentification}/status':
    get:
      summary: Batch payment status
      description: |
        Resource for entering a new batch payment.
      operationId: '-getBatchPaymentStatus'
      tags:
        - Batch Payments
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
  '/my/batchpayments/{transactionIdentification}/sign/{signId}':
    get:
      summary: Step I. Batch payment authorization detail
      description: >
        - To identify the status and scenarios of batch payment authorization.

        - Part of the response is also the set of scenarios that may contain one
        or more authorisation scenarios. If more scenarios are returned, it is
        up to the client to select what scenario to choose. The power of
        verifying each scenario should correspond to the power of other
        scenarios, or the scenarios are mutually replaceable.

        - Each scenario is defined as the sequence of codes of particular
        authorization methods.

        - Each bank may define and describe in its documentation its own
        authorization scenarios.

        - CODE of authorization methods of these scenarios is used in the
        response of this resource.



        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-getBatchPaymentAuthorizationDetail'
      tags:
        - Batch Payments
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
    post:
      summary: Step II. Batch Payment authorization initiation - specific for each bank
      description: >
        - This resource is designed to **start a specific authorization method**
        from the selected scenario.

        - The input is the JSON object containing the required type of
        authorization method - **CODE** and all elements specific for that step.

        - The output of this resource is an overview of values required for
        completing the authorization.

        - **E.g., for CODE corresponding to the federated authorization, the
        response will be URL and parameters for redirecting to the federated
        authorization page.**

        - And, for instance, for CODE corresponding to authorization through the
        OTP code sent by SMS, the response will only be the confirmation of
        sending the code. The sending as such is initiated by the bank.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of API calling
          * **Use certificate:**  request requires the use of the qualified third-party certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-postBatchPaymentAuthorizationInitiation'
      tags:
        - Batch Payments
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
    put:
      summary: >-
        Step III. Batch Payment authorization initiation – specific for each
        bank
      description: >
        - An optional resource designed for the finalization of the
        authorization process. 

        - The resource may be purely indicative or returns information on
        whether the authorization process was completed and with what result. 

        - E.g., in the case of federated authorization.

        - Or what input, e.g. for entering the received OTP for the SMS method.

        - Then the output is information on the authorization and also OTP
        verification.


        **Resource characteristics:**
          * **Authorization:**  request requires the authorization of user/client as part of the API calling
          * **Use certificate:**  request requires the use of the third-party qualified certificate
          * **Paging:** no
          * **Sorting:**  no
          * **Filtering:**  no
      operationId: '-putBatchPaymentAuthorizationInitiation'
      tags:
        - Batch Payments
      security:
        - OAuth2:
            - PISP
            - pisp.payments
          ClientCert: []
          ApiKey: []
tags:
  - name: Account information
    description: >
      Specification of API Information about the account contains a description
      of resources for the acquisition of  information about the payment
      account/accounts of the bank client.


      **Overview of resources:**
        * GET list of client payment accounts
        * GET account balance
        * GET transaction overview
        * GET list of client’s standing orders
        * GET list of client’s domestic direct debits Consents
  - name: Payment Initiation
    description: >
      Specification of API Payment Initiation contains a description of
      resources for the payment initiation and the Balance Check of the payer
      (client) at a specific financial institution.


      **Overview of resources:**
        * POST query for balance check
        * POST new single payment (Payment Initiation)
        * GET status of entered/initiated single payment
        * DELETE deletion of the entered and not authorised single payment
        * POST generation of authorization ID for single payment
        * Single payment authorisation
           * GET Step I. payment authorisation detail
           * POST Step II. payment authorisation initiation - specific for each bank
           * PUT Step III. payment authorisation finalization - specific for each bank
        * GET List of PSU authorizations
  - name: Standing Orders
    description: >
      Overview of resources for the establishment, authorization and
      administration of standing orders.


      **Overview of resources:**
        * POST New standing order - instruction initiation 
          * GET Standing order authorization Step I
          * POST Standing order authorization Step II
          * PUT Standing order authorization Step III
        * GET Standing order detail
        * GET Standing order status
        * PUT Existing standing order change
        * DELETE unauthorised standing order
  - name: Direct Debits
    description: >
      Overview of resources for the establishment, authorization and
      administration of domestic direct debit consent.


      **Overview of resources:**
        * POST Domestic direct debit consent - instruction initiation
          * GET Direct debit authorization Step I
          * POST Direct debit authorization Step II
          * PUT Direct debit authorization Step III
        * GET Domestic direct debit Consent detail
        * GET List of client’s domestic direct debits Consents
        * PUT Change of existing Domestic direct debit Consent
        * DELETE Domestic direct debit Consent delete

        * POST Domestic direct debit order - instruction initiation
        * GET Domestic direct debit order detail
        * DELETE Domestic direct debit order
        * GET Domestic direct debit order status
  - name: Batch Payments
    description: >
      Overview of resources for the establishment, authorization and
      administration of batch payments.


      **Overview of Batch payment - bulk authorization resources:**
        * POST New batch payment - instruction initiation 
          * GET Batch payment authorization Step I
          * POST Batch payment authorization Step II
          * PUT Batch payment authorization Step III
        * DELETE Batch payment
        * GET Batch payment status
  - name: Balance check
    description: >
      Specification of API Balance Check contains a description of resources for
      the acquisition of information on sufficient funds of the payer (client)
      at a specific financial institucion.


      **Overview of resources:**
        * POST query for Balance Check

